export const GET_ALL_COURSE_LIST = "GET_ALL_COURSE_LIST";
export const GET_CHAPTER_LIST = "GET_CHAPTER_LIST";
export const GET_LESSON_LIST = "GET_LESSON_LIST";
export const BATCH_REMOVE_LESSON_LIST = "BATCH_REMOVE_LESSON_LIST";
